instagram/accounts/urls.py
from django.urls import path

from accounts.views import (
    LoginView, LogoutView, RegisterView, DetailUserView,
    UserProfileUpdateView, ChangePasswordView, SearchProfileView,
    FollowingView
)

urlpatterns = []

accounts_urls = [
    path('login/', LoginView.as_view(), name='login_view'),
    path('logout/', LogoutView.as_view(), name='logout_view'),
    path('register/', RegisterView.as_view(), name='register_view'),
    path('profile/<int:pk>', DetailUserView.as_view(), name='detail_user_view'),
    path('profile/update', UserProfileUpdateView.as_view(), name='update_profile'),
    path('profile/change_password', ChangePasswordView.as_view(), name='change_password'),
    path('profile/search', SearchProfileView.as_view(), name='search_profile'),
    path('profile/<int:pk>/following', FollowingView.as_view(), name='following')
]

urlpatterns += accounts_urls

instagram/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from core import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls')),
    path('api/v1/', include('api_v1.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

instagram/accounts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from phonenumber_field.modelfields import PhoneNumberField


class Profile(models.Model):
    GENDER_CHOICES = [
        ('MALE', 'Мужской'),
        ('FEMALE', 'Женский')
    ]
    user = models.OneToOneField(
        get_user_model(), related_name='profile',
        on_delete=models.CASCADE, verbose_name='Пользователь'
    )
    avatar = models.ImageField(upload_to='user_pics', verbose_name='Аватар')
    user_information = models.TextField(max_length=2000, null=True, blank=True,
                                        verbose_name='Информация о пользователе')
    phone_number = PhoneNumberField(unique=True, region='KZ', null=True, blank=True,  verbose_name='Номер телефона')
    gender = models.CharField(max_length=6, null=True, blank=True, choices=GENDER_CHOICES, verbose_name='Пол')
    subscriptions = models.ManyToManyField(
        get_user_model(), related_name='subscribers', verbose_name='Подписки', blank=True
    )

    def __str__(self):
        return f'{self.user.get_full_name()}'

    class Meta:
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'

instagram/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError

from accounts.models import Profile


class UserCreationForm(forms.ModelForm):
    username = forms.CharField(max_length=50, label='Имя пользователя', required=True)
    password = forms.CharField(
        label='Пароль', strip=False, required=True, widget=forms.PasswordInput
    )
    password_confirm = forms.CharField(
        label='Подтвердите пароль', strip=False, required=True, widget=forms.PasswordInput
    )
    email = forms.EmailField(label='Почта', required=True)

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        password_confirm = cleaned_data.get('password_confirm')
        if password and password_confirm and password != password_confirm:
            raise ValidationError('Пароли не совпадают!')

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data.get('password'))
        if commit:
            user.save()
        return user

    class Meta:
        model = get_user_model()
        fields = [
            'username', 'first_name', 'password', 'password_confirm', 'email'
        ]


class ProfileCreationForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ['user']


class UserChangeForm(forms.ModelForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = get_user_model()
        fields = ['username', 'first_name', 'email']


class ProfileChangeForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ['user', 'subscriptions']


class PasswordChangeForm(forms.ModelForm):
    password = forms.CharField(strip=False, widget=forms.PasswordInput)
    password_confirm = forms.CharField(strip=False, widget=forms.PasswordInput)
    password_old = forms.CharField(strip=False, widget=forms.PasswordInput)

    def clean_password_confirm(self):
        password = self.cleaned_data.get('password')
        password_confirm = self.cleaned_data.get('password_confirm')
        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError('Пароли не совпадают!')
        return password_confirm

    def clean_password_old(self):
        password_old = self.cleaned_data.get('password_old')
        if not self.instance.check_password(password_old):
            raise forms.ValidationError('Не правильно указан старый пароль!')
        return password_old

    def save(self, commit=True):
        user = self.instance
        user.set_password(self.cleaned_data['password_confirm'])
        if commit:
            user.save()
        return user

    class Meta:
        model = get_user_model()
        fields = ['password', 'password_confirm', 'password_old']


class SearchForm(forms.Form):
    search = forms.CharField(max_length=100, required=False)


class FollowForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ['subscriptions', 'user', 'avatar']

instagram/accounts/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.urls import reverse

from accounts.forms import (
    UserCreationForm, ProfileCreationForm, UserChangeForm,
    ProfileChangeForm, PasswordChangeForm, SearchForm,
    FollowForm
)
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.views.generic import DetailView, UpdateView, ListView

from accounts.models import Profile
from webapp.helpers import SearchView
from webapp.models import Posts


class HomePageView(LoginRequiredMixin, ListView):
    model = get_user_model()
    template_name = 'profile/home_page.html'
    context_object_name = 'user_obj'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['posts'] = Posts.objects.filter(user_id__in=self.request.user.profile.subscriptions.all()).order_by(
            '-created_at')
        return context


class LoginView(View):

    def get(self, request, *args, **kwargs):
        context = {
            'next': request.GET.get('next')
        }
        return render(request, 'registration/login.html', context)

    def post(self, request, *args, **kwargs):
        context = {}
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        next_page = request.GET.get('next')
        if user is not None:
            login(request, user)
            if next_page:
                return redirect(next_page)
            return redirect('home_page')
        else:
            context['has_error'] = True
        return render(request, 'registration/login.html', context=context)


class LogoutView(View):

    def get(self, request, *args, **kwargs):
        logout(self.request)
        return redirect('home_page')


class RegisterView(View):
    def get(self, request, *args, **kwargs):
        form = UserCreationForm()
        profile_form = ProfileCreationForm()
        genders = Profile.GENDER_CHOICES
        return render(request, 'registration/register.html', context={
            'form': form,
            'genders': genders,
            'profile_form': profile_form
        })

    def post(self, request, *args, **kwargs):
        form = UserCreationForm(data=request.POST)
        profile_form = ProfileCreationForm(request.POST, request.FILES)
        next_page = request.GET.get('next')
        if form.is_valid() and profile_form.is_valid():
            user = form.save()
            user_profile = profile_form.save(commit=False)
            user_profile.user = user
            user_profile.save()
            login(request, user)
            if next_page is not None:
                return redirect(next_page)
            return redirect('home_page',)
        return render(request, 'registration/register.html', context={
            'form': form,
            'genders': Profile.GENDER_CHOICES,
            'profile_form': profile_form
        })


class DetailUserView(DetailView):
    model = get_user_model()
    template_name = 'profile/detail_user.html'
    context_object_name = 'user_obj'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['posts'] = self.object.user_post.order_by('-created_at')
        context['user'] = self.kwargs.get('pk')
        return context


class UserProfileUpdateView(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    form_class = UserChangeForm
    template_name = 'profile/user_profile_change.html'

    def get_object(self, queryset=None):
        return self.model.objects.get(id=self.request.user.id)

    def get_context_data(self, **kwargs):
        if 'profile_form' not in kwargs:
            kwargs['profile_form'] = self.get_profile_form()
            kwargs['genders'] = Profile.GENDER_CHOICES
        return super().get_context_data(**kwargs)

    def get_profile_form(self):
        form_kwargs = {'instance': self.object.profile}
        if self.request.method == 'POST':
            form_kwargs['data'] = self.request.POST
            form_kwargs['files'] = self.request.FILES
        return ProfileChangeForm(**form_kwargs)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        profile_form = self.get_profile_form()
        if form.is_valid() and profile_form.is_valid():
            return self.form_valid(form, profile_form)
        else:
            return self.form_invalid(form, profile_form)

    def form_invalid(self, form, profile_form):
        context = self.get_context_data(
            form=form, profile_form=profile_form,
            genders=Profile.GENDER_CHOICES
        )
        return self.render_to_response(context)

    def form_valid(self, form, profile_form):
        response = super().form_valid(form)
        profile_form.save()
        return response

    def get_success_url(self):
        return reverse('detail_user_view', kwargs={'pk': self.object.pk})


class ChangePasswordView(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    template_name = 'profile/change_password.html'
    form_class = PasswordChangeForm

    def get_object(self, queryset=None):
        return self.model.objects.get(id=self.request.user.id)

    def get_success_url(self):
        return reverse('login_view')


class SearchProfileView(SearchView):
    template_name = 'profile/search_users.html'
    model = get_user_model()
    context_object_name = 'profiles'
    search_form = SearchForm
    search_fields = {
        'username': 'icontains',
        'first_name': 'icontains',
        'email': 'icontains'
    }


class FollowingView(UpdateView):
    model = get_user_model()
    form_class = FollowForm
    template_name = 'profile/detail_user.html'
    context_object_name = 'user_obj'

    def post(self, request, *args, **kwargs):
        form = self.form_class(data=request.POST)
        if form.is_valid():
            profile = self.kwargs.get('pk')
            request_user = self.request.user
            request_user.profile.subscriptions.add(profile)
            url = reverse('detail_user_view', kwargs={
                'pk': profile
            })
            return HttpResponseRedirect(url)
        return render(request, self.template_name, context={'form': form})

instagram/accounts/templates/profile/change_password.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div style="padding: 100px 0 0 350px">
        <div class="border" style="background-color: white; width: 600px">
            <div style="text-align: center">
                <img style="width: 300px;" src="{% static 'image/inst.png' %}" alt="">
            </div>
            <form action="{% url 'change_password' %}" method="POST">
                {% csrf_token %}
                <div style="padding: 20px 0 0 100px">
                    <input class="border"
                           style="background-color: #FAFAFA; border-radius: 5px; padding: 7px 70px; text-align: center"
                           type="password" name="password" id="password" placeholder="Пароль"/>
                </div>
                <div style="padding: 20px 0 0 100px">
                    <input class="border"
                           style="background-color: #FAFAFA; border-radius: 5px; padding: 7px 70px; text-align: center"
                           type="password" name="password_confirm" id="password_confirm"
                           placeholder="Повторите пароль"/>
                </div>
                <div style="padding: 20px 0 0 100px">
                    <input class="border"
                           style="background-color: #FAFAFA; border-radius: 5px; padding: 7px 70px; text-align: center"
                           type="password" name="password_old" id="password_old" placeholder="Старый пароль"/>
                </div>
                <div style="padding: 20px 0 0 100px">
                    <button class="border border-1" style="background-color: #3897F0; padding: 10px 128px"
                            type="submit"><b style="color: white">Change password</b></button>
                </div>
                <div style="padding-top: 100px"></div>
            </form>
        </div>
    </div>
{% endblock %}

instagram/accounts/templates/profile/detail_user.html
{% extends 'base.html' %}


{% block content %}
    <div style="background-color: #FAFAFA; display: flex; padding-top: 70px; justify-content: center;">
        <div style="display: inline-block; border-radius: 50%; overflow: hidden; width: 200px; height: 200px">
            {% if user_obj.profile.avatar %}
                <img style="width: 100%; height: 100%; object-fit: cover" src="{{ user_obj.profile.avatar.url }}"
                     alt="...">
            {% endif %}
        </div>
        <div style="padding-left: 300px">
            <div style="display: flex">
                <div>
                    <h2>{{ user_obj.username }}</h2>
                </div>
                <div style="padding-left: 50px">
                    {% if request.user.id == user_obj.id %}
                        <a class="btn btn-light border" href="{% url 'update_profile' %}"><b>Редактировать
                            профиль</b></a>
                    {% endif %}
                </div>
            </div>
            <br>
            {% if request.user.pk == user %}
                <div style="display: flex; width: 400px; justify-content: space-between">
                    <p>{{ user_obj.user_post.count|default:0 }} публикаций</p>
                    <p>{{ user_obj.subscribers.count|default:0 }} подписчиков</p>
                    <p>Подписок {{ user_obj.profile.subscriptions.count|default:0 }}</p>
                </div>
            {% else %}
                <div style="display: flex; width: 500px; justify-content: space-between">
                    <p>{{ user_obj.user_post.count|default:0 }} публикаций</p>
                    <p>{{ user_obj.subscribers.count|default:0 }} подписчиков</p>
                    <p>Подписок {{ user_obj.profile.subscriptions.count|default:0 }}</p>
                    <form action="{% url 'following' user_obj.pk %}" method="POST">
                        {% csrf_token %}
                        {% if user_obj in request.user.profile.subscriptions.all %}
                            <button style="font-size: 10px" class="btn btn-primary disabled" type="submit">подписаться
                            </button>
                        {% else %}
                            <button style="font-size: 10px" class="btn btn-primary" type="submit">подписаться</button>
                        {% endif %}
                    </form>
                </div>
            {% endif %}
            <p>{{ user_obj.first_name|default:'' }}</p>
            <div style="width: 600px">
                <p>{{ user_obj.profile.user_information|linebreaksbr|default:'' }}</p>
            </div>
        </div>
    </div>
    <br>
    <br>
    <div style="display: flex; flex-wrap: wrap; padding-left: 90px">
        {% for post in posts %}
            <div class="card" style="width: 400px;">
                <a href="{% url 'post_detail' post.pk %}"><img style="min-height: 600px" src="{{ post.image.url }}" class="card-img-top" alt="..."></a>
            </div>
        {% empty %}
            <h1 style="display: flex; justify-content: center; color: gray">Публикации отсуствуют</h1>
        {% endfor %}
    </div>
{% endblock %}

instagram/accounts/templates/profile/search_users.html
{% extends 'base.html' %}

{% block content %}
    <br>
    <h1 class="title">{{ title }}</h1>
    <br>
    <div class="title_border"></div>
    <br>
    {% if profiles %}
        {% include 'partials/profile_list.html' %}
    {% else %}
        {% include 'partials/profile_list.html' %}
    {% endif %}
{% endblock %}

instagram/accounts/templates/profile/user_profile_change.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div style="text-align: center">
        <img style="width: 300px;" src="{% static 'image/inst.png' %}" alt="">
    </div>
    <form action="{% url 'update_profile' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'partials/user_form.html' %}
        {% include 'partials/profile_form.html' %}
        <div style="display: flex">
            <input type="submit" value="UPDATE" style="background-color: #3897F0; color: white"
                   class="border btn">
            <a style="background-color: #3897F0; color: white; margin-left: 20px" class="btn"
               href="{% url 'change_password' %}">CHANGE PASSWORD</a>
        </div>
        <div style="padding-top: 100px"></div>
    </form>
{% endblock %}